# Generated by Django 4.2.20 on 2025-05-09 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_deposited', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('last_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('basic_eps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume', models.PositiveBigIntegerField(blank=True, null=True)),
                ('market_cap', models.PositiveBigIntegerField(blank=True, null=True)),
                ('revenue', models.PositiveBigIntegerField(blank=True, null=True)),
                ('debt', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ipo_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.portfolio'),
        ),
        migrations.AddField(
            model_name='holding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('portfolio', 'stock')},
        ),
    ]
