# Generated by Django 5.2.1 on 2025-05-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_holding_portfolio_stock_delete_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='basic_eps',
            new_name='pe_ratio',
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
